# Generated by Django 5.2.5 on 2025-08-27 13:05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_remove_project_owned_by_projectmembership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmembership",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, verbose_name="ID"
            ),
        ),
    ]
