# Generated by Django 5.2.5 on 2025-08-27 13:11

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    ProjectMembership = apps.get_model("projects", "ProjectMembership")
    for row in ProjectMembership.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_add_projectmembership_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
