# Generated by Django 5.2.5 on 2025-08-27 14:05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_populate_projectmembership_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmembership",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
