# Generated by Django 5.2.5 on 2025-09-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_projectmembership_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="normalised_domain",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
    ]
