# Generated by Django 5.2.5 on 2025-09-15 10:06

import re

from django.db import migrations


def gen_normalised_domain(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for row in Project.objects.all():
        normalised = row.domain.lower()
        normalised = re.sub(r"^https://", "", normalised)
        normalised = re.sub(r"^www\.", "", normalised)
        normalised = normalised.rstrip("/")

        row.normalised_domain = normalised
        row.save(update_fields=["normalised_domain"])


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_add_project_normalised_domain"),
    ]

    operations = [
        migrations.RunPython(
            gen_normalised_domain, reverse_code=migrations.RunPython.noop
        ),
    ]
