# Generated by Django 5.2.5 on 2025-09-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_populate_project_normalised_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="normalised_domain",
            field=models.CharField(editable=False, max_length=256),
        ),
    ]
