# Generated by Django 5.2.5 on 2025-09-15 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_alter_project_normalised_domain"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("normalised_domain",),
                name="unique_normalised_domain",
                violation_error_message="This domain is already in use with another project.",
            ),
        ),
    ]
