services:
  app:
    build:
      context: .
      args:
        IMAGE: ghcr.io/nationalarchives/tna-python-django
        IMAGE_TAG: preview
    environment:
      - RUNTIME=develop
      - DJANGO_SETTINGS_MODULE=config.settings.develop
      - SECRET_KEY=abc123
      - NPM_DEVELOP_COMMAND=dev
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_USERNAME=admin
      - COOKIE_DOMAIN=localhost
      - CSP_STYLE_SRC_ELEM='self',fonts.googleapis.com,p.typekit.net,use.typekit.net
      - CSP_FONT_SRC='self',fonts.gstatic.com,use.typekit.net
    ports:
      - 65527:8080
    depends_on:
      - db
    volumes:
      - ./:/app
    command: ./run.sh

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  dev:
    image: ghcr.io/nationalarchives/tna-python-dev:preview
    volumes:
      - ./:/app

  docs:
    image: squidfunk/mkdocs-material
    volumes:
      - .:/docs
    ports:
      - 65526:8000

volumes:
  pgdata:
