# Generated by Django 5.1.6 on 2025-08-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("users", "0002_alter_user_email"),
        ("users", "0003_alter_user_managers_remove_user_username"),
    ]

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
