# Generated by Django 5.1.6 on 2025-03-26 18:05

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_forms", "0002_pathpattern"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pathpattern",
            name="unique_project_pattern",
        ),
        migrations.AddField(
            model_name="pathpattern",
            name="is_wildcard",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="pathpattern",
            constraint=models.UniqueConstraint(
                models.F("project"),
                django.db.models.functions.text.Lower("pattern"),
                models.F("is_wildcard"),
                name="unique_project_pattern",
                violation_error_message="You cannot use the same pattern twice in a project.",
            ),
        ),
    ]
