# Generated by Django 5.1.6 on 2025-04-01 15:37

import django.contrib.postgres.indexes
from django.conf import settings
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedback_forms",
            "0003_remove_pathpattern_unique_project_pattern_and_more",
        ),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name="pathpattern",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["pattern"], name="feedback_form_pattern_gin"
            ),
        ),
    ]
