# Generated by Django 5.2.5 on 2025-08-07 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedback_forms",
            "0003_remove_pathpattern_unique_project_pattern_and_more",
        ),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackform",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feedback_forms",
                to="projects.project",
            ),
        ),
    ]
