# Generated by Django 5.1.6 on 2025-02-26 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BinaryPrompt",
            fields=[
                (
                    "prompt_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="prompts.prompt",
                    ),
                ),
                (
                    "positive_answer_label",
                    models.CharField(default="Yes", max_length=64),
                ),
                (
                    "negative_answer_label",
                    models.CharField(default="No", max_length=64),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("prompts.prompt",),
        ),
    ]
