# Generated by Django 5.1.6 on 2025-02-26 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0002_binaryprompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="RangedPrompt",
            fields=[
                (
                    "prompt_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="prompts.prompt",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("prompts.prompt",),
        ),
        migrations.CreateModel(
            name="RangedPromptOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=64)),
                ("value", models.PositiveSmallIntegerField()),
                (
                    "ranged_prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="prompts.rangedprompt",
                    ),
                ),
            ],
        ),
    ]
