# Generated by Django 5.1.6 on 2025-03-11 15:48

import uuid

from django.db import migrations, models


def set_uuid(apps, schema_editor):
    RangedPromptOption = apps.get_model("prompts", "rangedpromptoption")
    for row in RangedPromptOption.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0003_rangedprompt_rangedpromptoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="rangedpromptoption",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=True,
                verbose_name="ID",
            ),
        ),
        migrations.RunPython(set_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="rangedpromptoption",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
