# Generated by Django 5.2.5 on 2025-09-14 19:30

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    ProjectAPIAccess = apps.get_model("api", "ProjectAPIAccess")
    for row in ProjectAPIAccess.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_projectapiaccess_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
