# Generated by Django 5.2.5 on 2025-09-14 19:35

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_populate_projectapiaccess_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectapiaccess",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="ID",
            ),
        )
    ]
