# Generated by Django 5.1.6 on 2025-03-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0004_rangedpromptoption_uuid"),
        ("responses", "0002_promptresponses"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="promptresponse",
            constraint=models.UniqueConstraint(
                models.F("response"),
                models.F("prompt"),
                name="unique_response_prompt",
                violation_error_message="You cannot submit the same prompt twice for a response.",
            ),
        ),
    ]
