# Generated by Django 5.1.6 on 2025-04-07 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_forms", "0002_pathpattern"),
        ("responses", "0003_promptresponse_unique_response_prompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="feedback_form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responses",
                to="feedback_forms.feedbackform",
            ),
        ),
    ]
