name: Run Python tests

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - uses: snok/install-poetry@v1
      with:
        version: 1.8.1
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: .venv
    - name: Install Poetry dependencies
      run: poetry install --no-interaction --no-root --with dev
      shell: bash
    - name: Collect static assets
      run: poetry run python manage.py collectstatic --no-input
      shell: bash
    - name: Django checks
      run: poetry run python manage.py check
      shell: bash
    - name: Check migrations
      run: poetry run python manage.py makemigrations --check --noinput
      shell: bash
    - name: Run Python tests
      run: poetry run python manage.py test
      shell: bash
